create table category (
    id bigint generated by default as identity,
    name varchar(255),
    primary key (id)
);
create table exchange_rate (
    value float(53),
    date timestamp(6),
    id bigint generated by default as identity,
    name varchar(255),
    primary key (id)
);
create table operation (
    limit_exceeded boolean not null,
    value float(53),
    category_id bigint,
    date timestamp(6),
    exchange_rate_id bigint,
    id bigint generated by default as identity,
    user_id bigint,
    currency varchar(255),
    primary key (id)
);
create table users (
    overall_product_limit float(53),
    overall_service_limit float(53),
    product_limit float(53),
    service_limit float(53),
    id bigint generated by default as identity,
    name varchar(255),
    primary key (id)
);
alter table if exists operation
    add constraint FKi2awma11xgw19x3vbmjdrj06p
        foreign key (exchange_rate_id) references exchange_rate;